[2023-04-02T03:40:17.135+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.upload_to_mongo_db manual__2023-04-02T03:40:11.715959+00:00 [queued]>
[2023-04-02T03:40:17.141+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.upload_to_mongo_db manual__2023-04-02T03:40:11.715959+00:00 [queued]>
[2023-04-02T03:40:17.142+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:40:17.142+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-02T03:40:17.143+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:40:17.150+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_mongo_db> on 2023-04-02 03:40:11.715959+00:00
[2023-04-02T03:40:17.155+0000] {standard_task_runner.py:55} INFO - Started process 1479 to run task
[2023-04-02T03:40:17.159+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'upload_to_mongo_db', 'manual__2023-04-02T03:40:11.715959+00:00', '--job-id', '426', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp6ovqevzl']
[2023-04-02T03:40:17.160+0000] {standard_task_runner.py:83} INFO - Job 426: Subtask upload_to_mongo_db
[2023-04-02T03:40:17.214+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag.upload_to_mongo_db manual__2023-04-02T03:40:11.715959+00:00 [running]> on host 0b6a9b63e384
[2023-04-02T03:40:17.263+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag
AIRFLOW_CTX_TASK_ID=upload_to_mongo_db
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T03:40:11.715959+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T03:40:11.715959+00:00
[2023-04-02T03:40:17.940+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 65, in upload_to_mongo_db
    coll.insert_many(s3_object)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list
[2023-04-02T03:40:17.953+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag, task_id=upload_to_mongo_db, execution_date=20230402T034011, start_date=20230402T034017, end_date=20230402T034017
[2023-04-02T03:40:17.966+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 426 for task upload_to_mongo_db (documents must be a non-empty list; 1479)
[2023-04-02T03:40:18.030+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-02T03:40:18.058+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
