[2023-04-02T03:14:54.389+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.upload_data_to_mongodb manual__2023-04-02T03:14:50.176843+00:00 [queued]>
[2023-04-02T03:14:54.396+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.upload_data_to_mongodb manual__2023-04-02T03:14:50.176843+00:00 [queued]>
[2023-04-02T03:14:54.397+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:14:54.397+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-02T03:14:54.398+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:14:54.406+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_data_to_mongodb> on 2023-04-02 03:14:50.176843+00:00
[2023-04-02T03:14:54.413+0000] {standard_task_runner.py:55} INFO - Started process 883 to run task
[2023-04-02T03:14:54.417+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'upload_data_to_mongodb', 'manual__2023-04-02T03:14:50.176843+00:00', '--job-id', '423', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpgqg8u7c0']
[2023-04-02T03:14:54.418+0000] {standard_task_runner.py:83} INFO - Job 423: Subtask upload_data_to_mongodb
[2023-04-02T03:14:54.480+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag.upload_data_to_mongodb manual__2023-04-02T03:14:50.176843+00:00 [running]> on host 0b6a9b63e384
[2023-04-02T03:14:54.700+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag
AIRFLOW_CTX_TASK_ID=upload_data_to_mongodb
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T03:14:50.176843+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T03:14:50.176843+00:00
[2023-04-02T03:14:54.813+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 43, in upload_data_to_mongodb
    coll.insert_many(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list
[2023-04-02T03:14:54.825+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag, task_id=upload_data_to_mongodb, execution_date=20230402T031450, start_date=20230402T031454, end_date=20230402T031454
[2023-04-02T03:14:54.832+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 423 for task upload_data_to_mongodb (documents must be a non-empty list; 883)
[2023-04-02T03:14:54.875+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-02T03:14:54.895+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
