[2023-04-04T04:10:27.165+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T04:10:22.650936+00:00 [queued]>
[2023-04-04T04:10:27.170+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T04:10:22.650936+00:00 [queued]>
[2023-04-04T04:10:27.171+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T04:10:27.171+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-04T04:10:27.172+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T04:10:27.179+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_azure_sql> on 2023-04-04 04:10:22.650936+00:00
[2023-04-04T04:10:27.184+0000] {standard_task_runner.py:55} INFO - Started process 820 to run task
[2023-04-04T04:10:27.188+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag2', 'upload_to_azure_sql', 'manual__2023-04-04T04:10:22.650936+00:00', '--job-id', '480', '--raw', '--subdir', 'DAGS_FOLDER/test_dag2.py', '--cfg-path', '/tmp/tmpa5wfsoru']
[2023-04-04T04:10:27.188+0000] {standard_task_runner.py:83} INFO - Job 480: Subtask upload_to_azure_sql
[2023-04-04T04:10:27.248+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T04:10:22.650936+00:00 [running]> on host 8206d31aa2d9
[2023-04-04T04:10:27.296+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag2
AIRFLOW_CTX_TASK_ID=upload_to_azure_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T04:10:22.650936+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T04:10:22.650936+00:00
[2023-04-04T04:10:28.800+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag2.py", line 108, in upload_to_azure_sql
    row.scores_away_total
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]String or binary data would be truncated in table 'cs779.dbo.basketball_games', column 'date'. Truncated value: '2'. (2628) (SQLExecDirectW)")
[2023-04-04T04:10:28.846+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag2, task_id=upload_to_azure_sql, execution_date=20230404T041022, start_date=20230404T041027, end_date=20230404T041028
[2023-04-04T04:10:28.877+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 480 for task upload_to_azure_sql (('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]String or binary data would be truncated in table 'cs779.dbo.basketball_games', column 'date'. Truncated value: '2'. (2628) (SQLExecDirectW)"); 820)
[2023-04-04T04:10:28.970+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-04T04:10:29.022+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
